### ISSUE TITLE
Bad json response

### ISSUE THREAD

**Issue by ipsumium** [Hernas/homebridge-salus-sq610#8]
**Describe The Bug:**

Entered the IP and euid of my device and i've got the attached error 
**To Reproduce:**

**Expected behavior:**

**Logs:**

```
[11/19/2024, 12:30:35 AM] [SalusSQ610HomebridgePlugin] Could not load the devices: SyntaxError: Unexpected token 'G', "G1" is not valid JSON
[11/19/2024, 12:30:35 AM] [SalusSQ610HomebridgePlugin] Could not load the devices: SyntaxError: Unexpected token 'G', "G1" is not valid JSON
    at JSON.parse (<anonymous>)
    at /homebridge/node_modules/@hernas/homebridge-salus-sq610/src/SalusConnect.ts:198:35
    at Array.forEach (<anonymous>)
    at SalusConnect.getDevices (/homebridge/node_modules/@hernas/homebridge-salus-sq610/src/SalusConnect.ts:190:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SalusSQ610HomebridgePlatform.discoverDevices (/homebridge/node_modules/@hernas/homebridge-salus-sq610/src/platform.ts:60:17)
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by california444** [comment]
Hello @ipsumium ,
thanks for reporting. Seems like deviceName must not always be a JSON object.
I created a PR to better handle this situation:
https://github.com/Hernas/homebridge-salus-sq610/pull/9

**Comment by bimusiek** [comment]
Thanks again @california444 I have pushed a new release 2.0.1 to NPM, @ipsumium can you please try the new version and report back?

**Comment by ipsumium** [comment]
![IMG_1032](https://github.com/user-attachments/assets/875931c2-68c9-40bc-a91d-349cb2491316)
it's working now, thanks
